### ISSUE TITLE
Mocking issue

### ISSUE THREAD

**Issue by Afrasyabafzal** [JuliaTesting/Mocking.jl#114]
I want to mock a function in test so that it always gives the same response i tried every possible things but not able to do that

**Comment by omus** [comment]
Can you provide the function signature of your patch and the function you want to mock? Alternatively, you may be able to determine the source of the problem yourself if you use `apply(...; debug::Bool=false)`.

Also, remember you need to use `Mocking.activate()` before you use `apply`.

**Comment by omus** [comment]
As of Mocking 0.8 you can debug with `ENV["JULIA_DEBUG"] = "Mocking"`

**Comment by omus** [comment]
Feel free to re-open this issue if these suggestions don't adequately solve your problem.
