### ISSUE TITLE
Asynchronous tasks can accidentally call patched functions

### ISSUE THREAD

**Issue by omus** [JuliaTesting/Mocking.jl#89]
In a scenario where an background asynchronous task is calling a function using `@mock` and a patch is applied during that time the async task can call the patched function instead of the original:

```julia
julia> using Mocking

julia> Mocking.activate()

julia> f() = 1
f (generic function with 1 method)

julia> function g(name, n)
           for i in 1:n
               x = @mock f()
               println(name, ": ", x)
               sleep(1)
           end
       end
g (generic function with 1 method)

julia> p = @patch f() = 2

Patch{typeof(f)}(f, var"##f_patch#259")

julia> @async g("async", 5)
async: Task (runnable) @0x000000012f5973101


julia> apply(p) do
           g("apply", 1)
       end
apply: 2
async: 2

julia> async: 1
async: 1
async: 1
julia>
```

**Comment by oxinabox** [comment]
We might want to push the variable that says if we are moving or not into a dynamically scoped context from 
ContextVariablesX.jl
I *think* that supports tasks and threads.
We use it in Checkpoints.jl

**Comment by omus** [comment]
I've confirmed that [ContextVariablesX.jl](https://github.com/tkf/ContextVariablesX.jl) does fix the issue as demonstrated above. I'll work on a PR for this.

@oxinabox I appreciate you bringing that package to my attention ❤️

**Comment by oxinabox** [comment]
@tkf any ideas?

**Comment by omus** [comment]
Issue was fixed in https://github.com/JuliaTesting/Mocking.jl/pull/112 but requires Julia 1.11
